### ISSUE TITLE
socket hang up 

### ISSUE THREAD

**Issue by Argetan** [simplyGits/MagisterJS#113]
```
{ FetchError: request to https://accounts.magister.net/account/login?returnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3DM6-zwin.magister.net%26redirect_uri%3Dhttps%253A%252F%252Fzwin.magister.net%252Foidc%252Fredirect_callback.html%26response_type%3Did_token%2520token%26scope%3Dopenid%2520profile%2520magister.ecs.legacy%2520magister.mdv.broker.read%2520magister.dnn.roles.read%26state%3D0fcc352eb497b47a4261a28ed39febe3%26nonce%3D9062833d20af9300089f2be6e9073e68%26acr_values%3Dtenant%253Azwin.magister.net failed, reason: socket hang up
    at ClientRequest.<anonymous> (/Users/julian/Delta/node_modules/node-fetch/lib/index.js:1444:11)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketOnEnd (_http_client.js:416:9)
    at TLSSocket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   'request to https://accounts.magister.net/account/login?returnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3DM6-zwin.magister.net%26redirect_uri%3Dhttps%253A%252F%252Fzwin.magister.net%252Foidc%252Fredirect_callback.html%26response_type%3Did_token%2520token%26scope%3Dopenid%2520profile%2520magister.ecs.legacy%2520magister.mdv.broker.read%2520magister.dnn.roles.read%26state%3D0fcc352eb497b47a4261a28ed39febe3%26nonce%3D9062833d20af9300089f2be6e9073e68%26acr_values%3Dtenant%253Azwin.magister.net failed, reason: socket hang up',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }
```

I started getting this error yesterday night. It appears to be related to the Magister authentication. I don't think it's related to the authentication code as that would have thrown an `incorrect username` error.

I tried it on two machines (Mac OS and Ubuntu), neither of them work.

**Comment by Sj3rd** [comment]
Its not the API I believe. Magister has been down for a couple hours. Cant login over here on Schoolmaster's official webclient. Just a matter of time I think.

**Comment by Argetan** [comment]
I should have tested that, won't load for me either. I'll leave the issue open for now until all services are working again.

**Comment by Argetan** [comment]
Everything appears to be working again.
