### ISSUE TITLE
How to see if magister account is parent...

### ISSUE THREAD

**Issue by 7kasper** [simplyGits/MagisterJS#120]
Here's an interesting one. I am adding support for parents and children. There is, however, no way to check if the account is a parent or child.

Inside the profileinfo there is a field saying isChild, this is even used inside the function children() which gets the parent's children.
https://github.com/simplyGits/MagisterJS/blob/2087f489d6a850943d31e49932935c0259fb6062/src/magister.js#L212-L232
This value is only ever true if the magister object comes from the children() function. Meaning that if I were to login with 'a' magister account I have no way of knowing if it is a child or parent until I call the children() method catch the following error (which occurs when calling children() on a child account) 
```
Unhandled rejection TypeError: Cannot read property 'map' of undefined
    at http.get.then.then.then.items (magbot3\node_modules\magister.js\lib\magister.js:386:124)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by 7kasper** [comment]
Whoops seems this is a duplicate of #89

**Comment by lieuwex** [comment]
is there a [privilege](privileges.js) matching this maybe?

**Comment by 7kasper** [comment]
@lieuwex yes there might be. Here's an overview of privileges of parent and my user account:
```javascript
Privileges { //Parent
  _items:
   [ { Naam: 'Cijfers', AccessType: [Array] },
     { Naam: 'Aanmeldingen', AccessType: [Array] },
     { Naam: 'WachtwoordWijzigen', AccessType: [Array] },
     { Naam: 'ProfielEmail', AccessType: [Array] },
     { Naam: 'DigitaalLesmateriaal', AccessType: [Array] },
     { Naam: 'EloOpdracht', AccessType: [Array] },
     { Naam: 'Studiewijzers', AccessType: [Array] },
     { Naam: 'Projecten', AccessType: [Array] },
     { Naam: 'Berichten', AccessType: [Array] },
     { Naam: 'Profiel', AccessType: [Array] },
     { Naam: 'ProfielMobiel', AccessType: [Array] },
     { Naam: 'Absenties', AccessType: [Array] },
     { Naam: 'Afspraken', AccessType: [Array] },
     { Naam: 'Roosterwijzigingen', AccessType: [Array] },
     { Naam: 'Kinderen', AccessType: [Array] },
     { Naam: 'Instellingen', AccessType: [Array] },
     { Naam: 'Activiteiten', AccessType: [Array] },
     { Naam: 'Ouderavond', AccessType: [Array] },
     { Naam: 'Vakkenpakketkeuze', AccessType: [Array] },
     { Naam: 'Lesperioden', AccessType: [Array] },
     { Naam: 'Examenresultaten', AccessType: [Array] },
     { Naam: 'Terugkommaatregelen', AccessType: [Array] },
     { Naam: 'Leerlingen', AccessType: [Array] },
     { Naam: 'Vakken', AccessType: [Array] },
     { Naam: 'ExamenAfnamemomenten', AccessType: [Array] },
     { Naam: 'Contactsoorten', AccessType: [Array] },
     { Naam: 'Absentiemeldingen', AccessType: [Array] },
     { Naam: 'Overeenkomsten', AccessType: [Array] } ] }
```
```javascript
Privileges { //Child
  _items:
   [ { Naam: 'Cijfers', AccessType: [Array] },
     { Naam: 'Aanmeldingen', AccessType: [Array] },
     { Naam: 'WachtwoordWijzigen', AccessType: [Array] },
     { Naam: 'ProfielEmail', AccessType: [Array] },
     { Naam: 'DigitaalLesmateriaal', AccessType: [Array] },
     { Naam: 'EloOpdracht', AccessType: [Array] },
     { Naam: 'Studiewijzers', AccessType: [Array] },
     { Naam: 'Projecten', AccessType: [Array] },
     { Naam: 'Bronnen', AccessType: [Array] },
     { Naam: 'Berichten', AccessType: [Array] },
     { Naam: 'Profiel', AccessType: [Array] },
     { Naam: 'ProfielMobiel', AccessType: [Array] },
     { Naam: 'Absenties', AccessType: [Array] },
     { Naam: 'Afspraken', AccessType: [Array] },
     { Naam: 'Aftekenen', AccessType: [Array] },
     { Naam: 'Contactpersonen', AccessType: [Array] },
     { Naam: 'Roosterwijzigingen', AccessType: [Array] },
     { Naam: 'Instellingen', AccessType: [Array] },
     { Naam: 'Activiteiten', AccessType: [Array] },
     { Naam: 'MataHuiswerk', AccessType: [Array] },
     { Naam: 'MataWidgets', AccessType: [Array] },
     { Naam: 'MataBerichtMappen', AccessType: [Array] },
     { Naam: 'MataKinderen', AccessType: [Array] },
     { Naam: 'MataDigitaalLesmateriaal', AccessType: [Array] },
     { Naam: 'MataEloOpdracht', AccessType: [Array] },
     { Naam: 'MataBerichten', AccessType: [Array] },
     { Naam: 'MataContactpersonen', AccessType: [Array] },
     { Naam: 'MataStudiewijzer', AccessType: [Array] },
     { Naam: 'MataProjecten', AccessType: [Array] },
     { Naam: 'MataRoosterwijzigingen', AccessType: [Array] },
     { Naam: 'MataAftekenen', AccessType: [Array] },
     { Naam: 'Keuzewerktijd', AccessType: [Array] },
     { Naam: 'Oauth', AccessType: [Array] },
     { Naam: 'LeerlingAutorisatie', AccessType: [Array] },
     { Naam: 'Lesperioden', AccessType: [Array] },
     { Naam: 'Persoonsgegevens', AccessType: [Array] },
     { Naam: 'Examenresultaten', AccessType: [Array] },
     { Naam: 'Terugkommaatregelen', AccessType: [Array] },
     { Naam: 'Leerlingen', AccessType: [Array] },
     { Naam: 'Vakken', AccessType: [Array] },
     { Naam: 'ExamenAfnamemomenten', AccessType: [Array] },
     { Naam: 'Contactsoorten', AccessType: [Array] },
     { Naam: 'Overeenkomsten', AccessType: [Array] } ] }
```

The `Ouderavond` privilege? >.<
The `Kinderen` priviledge might be universal.

**Comment by Argetan** [comment]
The `Mata`-stuff seems to be given to only children, perhaps it could be used to check if someone is a child?

**Comment by lieuwex** [comment]
Mata is from the good old pre-magister-6 time, birthplace of some good friendships, however, since it's old I wouldn't really depend on it I guess? The `kinderen` privilege sure sounds good, that should do the trick I guess?

Having the `kinderen` privilege means parent account, if absent, it's a child account instead.

**Comment by Argetan** [comment]
I created a PR regarding this issue, it should probably be tested by a parent account as well.
