### ISSUE TITLE
Authenticating with token results in error

### ISSUE THREAD

**Issue by Sj3rd** [simplyGits/MagisterJS#95]
(api version alpha.2)
When logging in with a token, an error is given:
```
something went wrong: TypeError: setToken(...).then is not a function
    at \node_modules\magister.js\lib\magister.js:522:36
    at Generator.next (<anonymous>)
    at step (\node_modules\magister.js\lib\magister.js:132:191)
    at \node_modules\magister.js\lib\magister.js:132:437
    at new Promise (<anonymous>)
    at \node_modules\magister.js\lib\magister.js:132:99
    at Magister.login (\node_modules\magister.js\lib\magister.js:589:5)
    at Promise.resolve.then (\node_modules\magister.js\lib\magister.js:624:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by gruijter** [comment]
@lieuwex I tested alpha4. It now works correctly with token 👍

**Comment by lieuwex** [comment]
Great! All credits to @idiidk of course :p
